Atualizar para o RN 0.70.1
idopterlabs/react-native-boilerplate pull request #3
Opened 2022-09-30 01:18 UTC by luccasalves

2022-09-30 12:51 UTC, TiagoDanin requested changes

2022-09-30 12:51 UTC, TiagoDanin commented on android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
O header desse para esse arquivo não foi atualizado

2022-09-30 14:10 UTC, TiagoDanin commented
Android status:
Tudo funcionando como esperado, mas o Select é diferente do input, consegue alterar a bordar do Select para 6px?
![image](https://user-images.githubusercontent.com/5731176/193288265-f84e7e16-f342-4e82-b65c-ad6601450b18.png)

Os testes estão falhando após atualização das bibliotecas de testes, por favor atualizar os testes

2022-09-30 14:36 UTC, TiagoDanin requested changes
Status iOS:
App ok, não funcionar pois o registro está com nome diferente, mas após a troca tudo ocorre normal. Por favor corrigir para podermos fazer merge. 

Outro detalhe é que o patch do paper é feito para uma versão diferente da que realmente é instaldo

2022-09-30 14:36 UTC, TiagoDanin commented on android/app/src/main/jni/CMakeLists.txt
> +project(rndiffapp_appmodules)
Modulo importado não existe

2022-09-30 14:36 UTC, TiagoDanin commented on ios/Template/AppDelegate.mm
> +    UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"RnDiffApp", initProps);
não existe registro para RnDiffApp

2022-09-30 16:36 UTC, lucasdasial commented on android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
Nao entendi

2022-09-30 16:55 UTC, TiagoDanin commented on android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
A função 
https://github.com/idopterlabs/react-native-boilerplate/blob/a346ba5643039731f179ff0d67bc851ceab60a34/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp#L25

tem o header por exemplo
https://github.com/idopterlabs/react-native-boilerplate/blob/a346ba5643039731f179ff0d67bc851ceab60a34/android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.h#L24

O que não bate, `name` != `&name` podendo causa problemas durante a compilação, todas as função devem ter chamadas equivalente declarados no header

2022-09-30 16:57 UTC, TiagoDanin commented on ios/Template/AppDelegate.mm
> +    UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"template", nill);
Nice, mas ainda não existe esse registro, o nome do pacote tem T maiúsculo

2022-09-30 17:02 UTC, TiagoDanin commented on ios/Template/AppDelegate.mm
> +    UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"template", nill);
PS: Props foram apagados também, sendo que são usados

2022-10-01 00:06 UTC, luccasalves commented on android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
Cara ainda não entendi,  no diff tava pedindo para trocar de name para &name

2022-10-03 12:00 UTC, TiagoDanin commented on android/app/src/main/jni/MainApplicationTurboModuleManagerDelegate.cpp
O problema continuar, apenas um header de uma função foi alterado, ainda falta duas

2022-10-03 13:30 UTC, TiagoDanin approved these changes
LGTM 💯

2022-10-03 13:31 UTC, merged